export const DELETE_ITEM_CONTENT = 'DELETE_ITEM_CONTENT';
export const FULL_SCREEN_LOADER = 'FULL_SCREEN_LOADER';
export const SELECT_VARIANT = 'SELECT_VARIANT';
export const PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION';
