# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Google Test Build to Firebase App Distribution"
  lane :distribute do
    build_ios_app()
    # build_ios_app is a built-in fastlane action.

    release = firebase_app_distribution(
      app: "1:306736103888:ios:0b180b4c063d62bbc6b9d5",
      testers: "okpunorrex@gmail.com",
      release_notes: "Lots of amazing new features to test out!",
      service_credentials_file:"zuraaya-d82fa-8c7b2856628f.json"
    )

  end
end
